name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ENVIRONMENT: pre

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.4
        env:
          POSTGRES_USER: preuser
          POSTGRES_PASSWORD: prepwd
          POSTGRES_DB: kudo-giver

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Get dependencies
      run: go get -t ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Examine source code
      run: go vet ./...
